### ISSUE TITLE
Please add DEBIAN_FRONTEND=noninteractive to tiny containers

### ISSUE THREAD

**Issue by voor** [paketo-buildpacks/stacks#12]
The last part `COPY --from=builder /tiny/ /` I think is removing all of the builder ENV variables you typically see, or maybe they're just never there?

**Comment by sclevine** [comment]
Given that `ubuntu:bionic` doesn't have this env var, and that `cloudfoundry/run:tiny` doesn't have apt anyways, how is this env var useful?

**Comment by voor** [comment]
It's useful in any image where you are calling `apt-get install` :cold_sweat:

**Comment by iainsproat** [comment]
@voor - I'd like to understand a little more about your use case. As @sclevine mentioned, apt-get/dpkg isn't installed on Tiny; are you installing apt-get/dpkg "manually" on top of CF Tiny?

cc @deskana

**Comment by kvedurmu** [comment]
@voor I'm going to go ahead and close this issue for now. Please feel free to reopen it with a response to the comments above.
