### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by cmoulliard** [paketo-buildpacks/stacks#18]
## Issue

The following image as defined within the stack example dont exist anymore
```
[stack]
build-image = "cloudfoundry/build:dev-base-cnb"
id = "io.buildpacks.stacks.bionic"
run-image = "cloudfoundry/run:dev-base-cnb"
```
During the execution of the following command, we got this error
```
pack create-builder cmoulliard/paketo-spring-boot-builder --builder-config builder.toml --verbose
Warning: run image cloudfoundry/run:dev-base-cnb is not accessible
ERROR: fetch build image: image cloudfoundry/build:dev-base-cnb does not exist on the daemon: not found
[snowdrop@h01-116 buildpack]$ docker pull cloudfoundry/build:dev-base-cnb
Error response from daemon: manifest for cloudfoundry/build:dev-base-cnb not found
```

**Comment by mdelillo** [comment]
Hi @cmoulliard, sorry for the delayed response. We've moved around and renamed the images a few times this year. The latest ones we recommend are `paketobuildpacks/build:base-cnb` and `paketobuildpacks/run:base-cnb` (or the equivalent `full`/`tiny` images).

Feel free to reopen if you're still experiencing issues.
