### ISSUE TITLE
Image Mirror on Azure

### ISSUE THREAD

**Issue by nebhale** [paketo-buildpacks/stacks#21]
Another image mirror should be created on Azure Cloud Registry.  The best naming option should likely be `paketo-buildpacks.azurecr.io` for consistency with other registries.

**Comment by martyspiewak** [comment]
Sorry for not responding to this earlier- I think there is an issue with our notifications for this repo so I will look into that.

Regarding your request, we will try to get on that this week. Thanks!

**Comment by dumez-k** [comment]
Closing this as public images are not currently supported by azure. 

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#how-do-i-enable-anonymous-pull-access
