### ISSUE TITLE
Add pt-online-schema-change to help run migrations on large tables

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/stacks#32]
## What happened?

For apps with very large datasets, [pt-online-schema-change](https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html) is useful for running migrations. It would be great if the stack included it or if there were a buildpack to install it.

**Comment by mdelillo** [comment]
Hey @genevieve, the use-case for this package is a little to specific for us to add it into the stacks but it could be a good fit for a buildpack. Feel free to open an RFC [here](https://github.com/paketo-buildpacks/rfcs/pulls).
