### ISSUE TITLE
Rename "bionic" directory to "base," and rename "base" directories to "dockerfile"

### ISSUE THREAD

**Issue by sclevine** [paketo-buildpacks/stacks#4]
The `bionic/` directory is published as `cloudfoundry/base`, so I think we should rename it to `base/` so that the directories match up to their published image names.

Additionally, the `base/` directory within each image type generates images that are really for use with Dockerfiles, so `dockerfile/` might be a more clear name.

**Comment by zmackie** [comment]
what about cflinuxfs3? `full/`

**Comment by zmackie** [comment]
Should cflinuxfs3 be called full too?

**Comment by sclevine** [comment]
Definitely, good catch
