### ISSUE TITLE
Tiny image is published to the wrong location on Docker Hub

### ISSUE THREAD

**Issue by sclevine** [paketo-buildpacks/stacks#6]
Here's the full scheme for image locations:

**base**

Builder: `cloudfoundry/cnb:base` (alias: `cloudfoundry/cnb:bionic`)
Build: `cloudfoundry/build:base-cnb`
Run: `cloudfoundry/run:base-cnb`
Build (without CNB stuff): `cloudfoundry/build:base`
Run (without CNB stuff): `cloudfoundry/run:base`

**full**

Builder: `cloudfoundry/cnb:full` (alias: `cloudfoundry/cnb:cflinuxfs3`)
Build: `cloudfoundry/build:full-cnb`
Run: `cloudfoundry/run:full-cnb`
Build/run (without CNB stuff): `cloudfoundry/build:full` (aliases: `cloudfoundry/cflinuxfs3`, `cloudfoundry/run:full`)

**tiny**

Builder: `cloudfoundry/cnb:tiny`
Build: `cloudfoundry/build:tiny-cnb` (same as `build:base`, but with tiny stack ID)
Run: `cloudfoundry/run:tiny-cnb`
Build (without CNB stuff): `cloudfoundry/build:base`  (use the **base** stack to build)
Run (without CNB stuff): `cloudfoundry/run:tiny`

We should remove `cloudfoundry/tiny` and `cloudfoundry/cnb-base`

**Comment by carlo-colombo** [comment]
@sclevine  I think that `cloudfoundry/tiny` should not be removed.  is the equivalent of `cloudfoundry/cflinuxfs3` and it could be used in the `FROM` statement of `Dockerfile` where does not make sense to have reference to CNB. 

I understand that the Run without CNB stuff (`cloudfoundry/run:tiny`) can be used with same effect but it still references to CNB concepts ( run).

**Comment by sclevine** [comment]
`cloudfoundry/run:tiny` is for use with a multi-stage Dockerfile, which is almost always employed when using distroless-like images. `cloudfoundry/run:tiny-cnb` is the equivalent CNB version of it.

The concept of build-time and runtime base images is not specific to CNB.
