### ISSUE TITLE
Could yj be added to cnb images to allow toml processing?

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/stacks#8]
Currently a shell-based CNB buildpack that wants to read TOML must first install  https://github.com/sclevine/yj. Could we add yj v4 to the base image please (jq is already installed)?

**Comment by drnic** [comment]
Bonus question - how is lifecycle's https://github.com/buildpack/lifecycle/blob/master/testdata/buildpack/bin/build#L10-L11 able to use `yj` without pre-installing it?

When I try to access `yj` on the cnb images it fails.

```
$ docker run -ti --entrypoint "" cloudfoundry/cnb-run:cflinuxfs3 yj
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"yj\": executable file not found in $PATH": unknown.
```

**Comment by zmackie** [comment]
Bionic has it:  https://github.com/cloudfoundry/stacks/blob/master/bionic/base/build/Dockerfile so I don’t see why it shouldn’t be on full/cflinuxfs3

**Comment by martyspiewak** [comment]
We are moving away from the cflinuxfs3/full-cf stack but the new `full` stack now has `yj` in it.

Both `full` and `base` use the `bionic` directory with different package lists so [adding yj](https://github.com/paketo-buildpacks/stacks/blob/main/bionic/dockerfile/build/Dockerfile#L15) happens in both base and full now.
